name: test_env_ocean_data_gateway
channels:
  - conda-forge
dependencies:
  - python=3.7
  ############## These will have to be adjusted to your specific project
  - aiohttp
  - cf_xarray>=0.6
  - dask
  - erddapy
  - flake8
  - h5netcdf
  - intake
  - intake-xarray
  - ioos_qc
  - ipython
  - isort
  - joblib
  - jupyter
  - jupyterlab
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - pint
  - pint-pandas
  - pint-xarray
  - pytest
  - requests
  - scipy
  - xarray
  ##############
  - pytest
  - pip:
    - codecov
    - pytest-cov
    - coverage[toml]
